// Code generated by mockery v2.34.2. DO NOT EDIT.

package mockedapp

import (
	context "context"

	models "github.com/moronvv/otus_golang_hw/hw12_13_14_15_calendar/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

type MockApp_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApp) EXPECT() *MockApp_Expecter {
	return &MockApp_Expecter{mock: &_m.Mock}
}

// CreateEvent provides a mock function with given fields: _a0, _a1
func (_m *MockApp) CreateEvent(_a0 context.Context, _a1 *models.Event) (*models.Event, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Event) (*models.Event, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Event) *models.Event); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Event) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type MockApp_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *models.Event
func (_e *MockApp_Expecter) CreateEvent(_a0 interface{}, _a1 interface{}) *MockApp_CreateEvent_Call {
	return &MockApp_CreateEvent_Call{Call: _e.mock.On("CreateEvent", _a0, _a1)}
}

func (_c *MockApp_CreateEvent_Call) Run(run func(_a0 context.Context, _a1 *models.Event)) *MockApp_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Event))
	})
	return _c
}

func (_c *MockApp_CreateEvent_Call) Return(_a0 *models.Event, _a1 error) *MockApp_CreateEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_CreateEvent_Call) RunAndReturn(run func(context.Context, *models.Event) (*models.Event, error)) *MockApp_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEvent provides a mock function with given fields: _a0, _a1
func (_m *MockApp) DeleteEvent(_a0 context.Context, _a1 int64) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_DeleteEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEvent'
type MockApp_DeleteEvent_Call struct {
	*mock.Call
}

// DeleteEvent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
func (_e *MockApp_Expecter) DeleteEvent(_a0 interface{}, _a1 interface{}) *MockApp_DeleteEvent_Call {
	return &MockApp_DeleteEvent_Call{Call: _e.mock.On("DeleteEvent", _a0, _a1)}
}

func (_c *MockApp_DeleteEvent_Call) Run(run func(_a0 context.Context, _a1 int64)) *MockApp_DeleteEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockApp_DeleteEvent_Call) Return(_a0 error) *MockApp_DeleteEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_DeleteEvent_Call) RunAndReturn(run func(context.Context, int64) error) *MockApp_DeleteEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvent provides a mock function with given fields: _a0, _a1
func (_m *MockApp) GetEvent(_a0 context.Context, _a1 int64) (*models.Event, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Event, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Event); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_GetEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvent'
type MockApp_GetEvent_Call struct {
	*mock.Call
}

// GetEvent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
func (_e *MockApp_Expecter) GetEvent(_a0 interface{}, _a1 interface{}) *MockApp_GetEvent_Call {
	return &MockApp_GetEvent_Call{Call: _e.mock.On("GetEvent", _a0, _a1)}
}

func (_c *MockApp_GetEvent_Call) Run(run func(_a0 context.Context, _a1 int64)) *MockApp_GetEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockApp_GetEvent_Call) Return(_a0 *models.Event, _a1 error) *MockApp_GetEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_GetEvent_Call) RunAndReturn(run func(context.Context, int64) (*models.Event, error)) *MockApp_GetEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvents provides a mock function with given fields: _a0
func (_m *MockApp) GetEvents(_a0 context.Context) ([]models.Event, error) {
	ret := _m.Called(_a0)

	var r0 []models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Event, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Event); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type MockApp_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockApp_Expecter) GetEvents(_a0 interface{}) *MockApp_GetEvents_Call {
	return &MockApp_GetEvents_Call{Call: _e.mock.On("GetEvents", _a0)}
}

func (_c *MockApp_GetEvents_Call) Run(run func(_a0 context.Context)) *MockApp_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockApp_GetEvents_Call) Return(_a0 []models.Event, _a1 error) *MockApp_GetEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_GetEvents_Call) RunAndReturn(run func(context.Context) ([]models.Event, error)) *MockApp_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEvent provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockApp) UpdateEvent(_a0 context.Context, _a1 int64, _a2 *models.Event) (*models.Event, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *models.Event) (*models.Event, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *models.Event) *models.Event); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *models.Event) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_UpdateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEvent'
type MockApp_UpdateEvent_Call struct {
	*mock.Call
}

// UpdateEvent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 int64
//   - _a2 *models.Event
func (_e *MockApp_Expecter) UpdateEvent(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockApp_UpdateEvent_Call {
	return &MockApp_UpdateEvent_Call{Call: _e.mock.On("UpdateEvent", _a0, _a1, _a2)}
}

func (_c *MockApp_UpdateEvent_Call) Run(run func(_a0 context.Context, _a1 int64, _a2 *models.Event)) *MockApp_UpdateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*models.Event))
	})
	return _c
}

func (_c *MockApp_UpdateEvent_Call) Return(_a0 *models.Event, _a1 error) *MockApp_UpdateEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_UpdateEvent_Call) RunAndReturn(run func(context.Context, int64, *models.Event) (*models.Event, error)) *MockApp_UpdateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
