[logger]
level = "DEBUG"

[server]
address = ":8080"

[storage]
type = "in-memory"  # in-memory, sql

[database]
dsn = "postgresql://"  # TODO: change
max_open_conns = 5
max_idle_conns = 2
conn_max_lifetime = "1m"
