with-expecter: True
packages:
  github.com/moronvv/otus_golang_hw/hw12_13_14_15_calendar/internal/storage:
    interfaces:
      EventStorage:
        config:
          filename: "events.go"
          dir: "{{.InterfaceDir}}/mocked"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocked{{.PackageName}}"
